### ISSUE TITLE
Add support for Bech32 format on entities keys

### ISSUE THREAD

**Issue by diegogurpegui** [KoalaSat/nostros#100]
Add support for the Bech32 format for entities keys (prefix "npub", "note", etc).
This will add compatibility with the rest of the clients, which are almost all implementing this. When copying the public key from other clients, almost always you get a "npub" one.

This is only meant to be a frontend/UI feature, internale hexadecimal is the way to go, as stated in the NIP.

NIP 19: https://github.com/nostr-protocol/nips/blob/master/19.md

**Comment by KoalaSat** [comment]
I'm working on this right now 🙂 my next PR will include this compatibility

**Comment by KoalaSat** [comment]
Included in https://github.com/KoalaSat/nostros/releases/tag/v0.2.0.0-alpha
