### ISSUE TITLE
please use proper versioning

### ISSUE THREAD

**Issue by IzzySoft** [KoalaSat/nostros#107]
currently, each and every APK at your releases seems to identify as

    package: name='com.nostros' versionCode='1' versionName='1.0'

so not only can a user never know what version is installed, but Android cannot tell if an APK you want to install is newer or not either (Android uses `versionCode` to tell them apart). So for the currently latest release, it should be `versionName: "0.2.0.1-alpha"` and `versionCode: 26` (as it's the 26th release; important with this one is just that you increase it with each version – how much you increase it is up to you, but you can never decrease it anymore without forcing all users to uninstall and reinstall).

Thanks in advance for taking care!

**Comment by diegogurpegui** [comment]
This is a good point and I agree.
However, that's probably left there unchecked on purpose since the app is not in stores right now.

What could be nice is to have the version of the app printed on some screen (eg: the bottom of Config screen).

**Comment by KoalaSat** [comment]
Believe it or not today I was thinking about it but I had to investigate how to properly do it, thanks for the hints @IzzySoft I'll change it for the next release

**Comment by KoalaSat** [comment]
https://github.com/KoalaSat/nostros/pull/110

**Comment by IzzySoft** [comment]
What a coincidence :rofl: Thanks, yes: exactly that was what I meant. So with that PR merged, the next APK built would show up as I described.

As for "not in the stores": Uhuh, that was part of the background to my question. I'm running the largest 3rd-party F-Droid repo with currently more than 1k apps ([see here](https://apt.izzysoft.de/fdroid)) and was considering to integrate your app there. With proper versioning (and especially `versionCode` always increased on release), I could finally do that. So if you're OK with this: I could pick some screenshots from your release messages – or you could provide a selection of your choice, plus some app description maybe? Ideally that could be set up using [Fastlane structures](https://gitlab.com/-/snippets/1895688) here in this repo; if I have description, screenshots & Co I could bundle a "starter package" for you.

**Comment by KoalaSat** [comment]
> What a coincidence 🤣 Thanks, yes: exactly that was what I meant. So with that PR merged, the next APK built would show up as I described.
> 
> As for "not in the stores": Uhuh, that was part of the background to my question. I'm running the largest 3rd-party F-Droid repo with currently more than 1k apps ([see here](https://apt.izzysoft.de/fdroid)) and was considering to integrate your app there. With proper versioning (and especially `versionCode` always increased on release), I could finally do that. So if you're OK with this: I could pick some screenshots from your release messages – or you could provide a selection of your choice, plus some app description maybe? Ideally that could be set up using [Fastlane structures](https://gitlab.com/-/snippets/1895688) here in this repo; if I have description, screenshots & Co I could bundle a "starter package" for you.

If you can do it for me it would be super awesome, you can take the screenshot but just be aware the next feature is drastically changing the UI, but I assume we can change those images at any point on the repo.

@frontends crypto is helping with the branding so maybe he can help with the description 🙂

**Comment by diegogurpegui** [comment]
Excellent :)

@KoalaSat I think the version and build bump should be included as part of the GitHub actions flow you have for building. That way it's automatic without you worrying about it. The build (`versionCode`) bump could be pretty automatic, but the versionName might require manual input in case you increase a minor version 0.x.0 or a patch 0.0.x for example.

**Comment by KoalaSat** [comment]
Yes I'm pretty sure there has to be some boilerplated GitHub action for that, I'll do the research, but probably of the action makes an extra commit obtaining the info from the triggered release can be fully automated, thanks for all the help!

Let us know if you need something else for the repo ⚡⚡

**Comment by IzzySoft** [comment]
> you can take the screenshot

Sorry to disappoint, but I'm not using Nostr so I'm not the best choice for this task. For starters, if you could provide the following, more can be added later:

* short description (max 80 chars)
* full description (a few lines describing the app and giving a clue of Nostr's concept so even those not familiar with it can get an idea). No need for a "fully polished" one, can always be improved later.
* an icon (128x128 to 512x512 px) and some screenshots (again, 3..5 suffice for starters, can be replaced and amended later)

It's totally fine to provide that just in a comment here, I'd then prepare the Fastlane structures and offer them back here for integration if you prefer. Or you give it a try yourself and have me cross-check :wink:

Once the listing is up, it can always be improved and built upon – see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) which I already linked above. Seeing the app size getting close to the limits of my repo already (30M per app; Nostros is already at 26M), per-ABI builds might be a good idea; I'd then pick the armeabi (most wide-spread support on older devices, and most 64bit devices support it as well) or if you prefer the arm64 APK for my repo. Once the app leaves "alpha stage" and is considered ready for a broader audience, I could guide you to get it listed at F-Droid.org (with all 4 ABIs then; disclosure: I'm one of the maintainers there).

**Comment by FrontendCrypto** [comment]
Hi! What do you think about something like this? I think this would be enough for now, we can always expand it later. @KoalaSat

**Short description**
The first Nostr client on Android. The only and truly uncensored social network.

**Full description**
Nostros is the first Nostr client for Android. Access a social network similar in appearance to Twitter, but decentralized and uncensored.

Nostros offers an extensive list of features that grows every day. Access the global feed or the feed of the people you follow. View all the content that you have liked, been mentioned or disliked.

You can also send tips to users through Lightning Network as well as associate your Nostr identity to your Twitter profile or domain.

Follow other users, or unfollow them. Indicate if you like their content, or if you don't like it. Comment on other people's posts or quote them.

Don't wait any longer and join the most social network thanks to Nostros.

**Screenshots**
![Screenshot_2023 01 12_18 49 44 996](https://user-images.githubusercontent.com/4659020/212144436-3592c3ff-88c2-4a42-a27d-2dfa4acfb03f.png)
![Screenshot_2023 01 12_19 00 32 629](https://user-images.githubusercontent.com/4659020/212144443-274578c5-41de-4a8e-a30f-11ae5c841646.png)
![Screenshot_2023 01 12_19 00 55 079](https://user-images.githubusercontent.com/4659020/212144445-f429096b-344c-492b-9719-099b219cfa75.png)
![Screenshot_2023 01 12_19 01 43 079](https://user-images.githubusercontent.com/4659020/212144446-8e27d385-04af-4e13-981d-db236eaf4c93.png)
![Screenshot_2023 01 12_19 02 06 579](https://user-images.githubusercontent.com/4659020/212144449-a5657ea7-50d6-489b-b891-3bb3420363e6.png)
![Screenshot_2023 01 12_19 02 28 313](https://user-images.githubusercontent.com/4659020/212144452-73ca39bb-941c-4926-bffb-4ed503fd7afb.png)

**Icons**
![128](https://user-images.githubusercontent.com/4659020/212141211-e4d9a99d-d879-4741-a5ed-34230f3a3e50.png)
![512](https://user-images.githubusercontent.com/4659020/212141213-95bb8729-0ed0-46c2-a727-b6c1d4583019.png)

**Comment by KoalaSat** [comment]
Awesome! Thank you! Please @IzzySoft let us know if you need anything else

**Comment by IzzySoft** [comment]
Awesome indeed! I'd just need the info if you would provide per-ABI builds. If not I can of course pick the "fat lady" – but then I could only hold the latest version available in my repo. A single ABI would most likely be below 15 M, so I could keep 2 versions (useful to prevent installation errors when a user e.g. just pulled the index right before a new version was added, and thus would try installing the version that was just purged – with 2 versions kept, it would still be there and the user would just get an update notification the next day).

Of course we could also move to per-ABI builds later – but depending on their setup, the switch might be a problem as usually each ABI has its specific `versionCode` (example: Flutter per default generates a code of `<ABI> x 1000 + versionCode` – so once my updater fetched the one with the highest ABI (4000 + `versionCode`) and it was the wrong one, switching to the other would mean users had to uninstall and re-install as you never can "downgrade" to a lower `versionCode`). This could of course be worked around by marking the first release with per-ABI builds `prerelease` (so my updater ignores it) and letting me know, so I can configure it accordingly on my end – and as soon as that's done the "pre-flag" can be removed again. We'd need some "constant patterns" in file names then so I can ensure the correct APK is fetched (usually `*armeabi-v7a*.apk` for ARMv7, `*arm64*.apk` for ARM64, and so on).

Just let me know your decision, and we're ready to go (as soon as the APK decided for is available).

**Comment by KoalaSat** [comment]
@IzzySoft sorry for answering late but right now we are totally focused on migrating the UI, what do you recommend? Don't now and eventually change and use the pre-ABI or it's fine to just for with one big version for now?

**Comment by IzzySoft** [comment]
As described it's preferable if I can hold more than one APK in my repo, so the per-ABI builds would be the way to go. And no pressure from my end: if your focus is now on migrating the UI, you probably won't release before that reached a "stable point". For the best "first impression", maybe wait for that – and take a look at per-ABI builds when the release comes close? Better have it lean and clean than haste and waste, do you agree? :smile:

An ETA would be nice to have – but if hard to give, I'll just wait and maybe chime in every now and then to see how things stand. I'll certainly do so when seeing a new release – but won't nag you twice a week :wink:

If you prefer going with the "fat lady" now and switch to per-ABI later, that can be done as well – see above for possible implications which are, hopefully, easily solved when planned in advance. I'd follow your preference then.

**Comment by KoalaSat** [comment]
Hi @IzzySoft again, we are done with the UI and entering the testing stage to be prepared for the Beta version.

I have been investigating  a little bit all the info you provided (thank you!) and certainly we can try to go with the per-ABI build. 😄 

My only doubt so far is how and from where you'll obtain the generated APK?

**Comment by KoalaSat** [comment]
Perfect that was my thought, I'll work on the GitHub action to generate both

**Comment by KoalaSat** [comment]
I make it work locally so I configured the github action, I'm planning to create a new release today/tomorrow so then we can test it out 💪 

https://github.com/KoalaSat/nostros/pull/160

**Comment by KoalaSat** [comment]
<img width="597" alt="Screenshot 2023-01-23 at 19 00 51" src="https://user-images.githubusercontent.com/111684255/214115010-5c1f9767-51e8-4cfd-8b5c-bfcecc5d79f2.png">

**Comment by IzzySoft** [comment]
That looks great! So whether you decide for armeabi or arm64, at that size I can keep 2 copies in my repo (so on update even those not yet having the latest index won't get an error-on-install as the previous APK is still available). With the "fat lady" aka "universal" I could only keep one.

So once they're up, just let me know which one you'd prefer me to pick. Thanks a lot!

**Comment by KoalaSat** [comment]
I think you mentioned you preffer to have `arm64` on your repo right? feel free to decide which one 😃 I'm still generating the universal for people that directly goes to github to download it.

**Comment by KoalaSat** [comment]
Also @FrontendCrypto I think with new UI those screenshots are obsolete

**Comment by IzzySoft** [comment]
> I think you mentioned you preffer to have `arm64` on your repo right? 

I used to take the `armeabi` APK for wider compatibility (and also for sustainability, supporting those using their hardware as long as it works while not neglecting that arm64 devices are around now for about 5 years, and being the majority of new devices). But I of course respect the wishes of the authors: so if you say you prefer me to pick arm64, I'm fine with that meanwhile (wasn't a year or 2 ago when 32bit devices were still more prominent than today).

> I'm still generating the universal for people who directly goes to github to download it.

By all means: yes, please do! If you'd have the universal and all the per-ABI builds here, everyone would have the full choice. That said, while I can check for myself once the APKs are up: what pattern are you using for `versionName`? Will they all share the same? If not, where will they differ: last digit or first (e.g. Flutter by default and for extra crazyness has them differ in the first digit; so if you start with a 2001 armeabi you'd have no chance switching to arm64 having a 1002 with the next release, which to me is absolute nuts).

> with new UI those screenshots are obsolete

Good point! I see you include some with your releases as well, so for starters I could pick some from there. Once set up, I can provide you the metadata in [Fastlane](https://gitlab.com/-/snippets/1895688) format to integrate with your repo here. Then you can update description, screenshots and all to your liking and changes will be pulled along with each new release.

**Comment by KoalaSat** [comment]
This is the pattern https://github.com/KoalaSat/nostros/blob/main/.github/workflows/android-build.yml#L56

**Comment by KoalaSat** [comment]
> Good point! I see you include some with your releases as well, so for starters I could pick some from there. Once set up, I can provide you the metadata in [Fastlane](https://gitlab.com/-/snippets/1895688) format to integrate with your repo here. Then you can update description, screenshots and all to your liking and changes will be pulled along with each new release.

Perfect let's do it like you say

**Comment by IzzySoft** [comment]
Ugh, guess I've chosen the wrong phrasing. I meant the "pattern" for `versionCode`. Would be good if e.g. armeabi had a smaller VC than arm64, so folks switching from an old 32bit device to a newer 64bit while transferring their apps and data would still be able to update from armeabi to arm64 then.

And great, I'll provide the metadata then (should I forget, be welcome to remind me). Looking forward to the next release then!

**Comment by KoalaSat** [comment]
@IzzySoft here you go https://github.com/KoalaSat/nostros/releases/tag/v0.2.1.2-alpha, I hope everything is correct, please let me know if we need to change something

**Comment by IzzySoft** [comment]
Thanks @KoalaSat! I've modified the description slightly (there are already 2 Nostr clients in my repo, so "the first" sounds a bit … strange :see_no_evil:). Will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.nostros) with the next sync today around 7 pm UTC. If you like what you see there: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley:

As promised, here's the [fastlane.zip](https://github.com/KoalaSat/nostros/files/10487973/fastlane.zip) with the metadata. Unzipped content should go directly to the document root (i.e. `/fastlane`). Feel free to replace the screenshots again (my framework compresses & resizes them – other places like F-Droid.org might keep them full-size) and build upon it (e.g. add per-release changelogs and a featureGraphic if you like – my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) may be a guidance with that.

Well, all done then I guess – so we can close this issue?

**Comment by IzzySoft** [comment]
Oh, PS: donations & Co. If you use [Github's `FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository), those details will be picked up automatically with each release. It doesn't support BC, so I've added your BC address manually already here.

**Comment by KoalaSat** [comment]
Thank you so much @IzzySoft I'll include the fastlane and check all your comments! this is great 🎉 🚀 !

**Comment by KoalaSat** [comment]
Also I just remeber you mentioned you have some info about how to upload this to F-Droid, do you?

**Comment by IzzySoft** [comment]
Gladly! Should there be any question left, just ask. Otherwise I guess we'll meet "over there" once you're ready :smiley:

**Comment by KoalaSat** [comment]
One last question @IzzySoft , what's the frequency of updates? When should I expect your repo to get the latest version?

**Comment by IzzySoft** [comment]
Within 24h of your tagging and attaching an APK. Updater runs once a day and publishes within an hour.

For more background: [see here](https://apt.izzysoft.de/fdroid/index/info) and [here](https://gitlab.com/IzzyOnDroid/repo/) :wink:

**Comment by KoalaSat** [comment]
Sorry for reusing this issue over and over @IzzySoft 😄 I think the category is not the right one,CNA I change it myself?

![Screenshot_20230130-212907](https://user-images.githubusercontent.com/111684255/215588375-f57326a5-fa4a-44e1-9553-59229803c66e.png)

And another question from @FrontendCrypto , of we don't include pictures for the French version, will it be a fallback to the English version?

**Comment by IzzySoft** [comment]
@KoalaSat what a coincidence! I just returned home from a meeting with frinds. Right at the time you wrote this comment, I discovered it when setting up a device with the F-Droid client – and returning home immediately fixed it :rofl: So it will be corrected with the next sync. Thanks for bringing it up! Strange it tried to separate the 3 Nostr clients that way with 2 different misspellings :see_no_evil: (that said, I still waiting for a catholic priest coming up with a 4th client called "PaterNostr" :speak_no_evil: :dash:

**Comment by KoalaSat** [comment]
hahaha perfect thanks for taking care of us! 😄

**Comment by FrontendCrypto** [comment]
Hi @IzzySoft. We have an issue. Description in full_description.txt differs from what I am seeing in your site. Any clues about why this could be happening?

![Screenshot_2023-02-13-13-42-31-495_com.android.chrome.jpg](https://user-images.githubusercontent.com/4659020/218464571-b71c9782-fbd7-4899-8248-1371f5941802.jpg)

![Screenshot_2023-02-13-13-44-11-636_com.github.android.jpg](https://user-images.githubusercontent.com/4659020/218464572-55ab7b4e-ccfa-4c10-b95c-454b7b194146.jpg)

**Comment by IzzySoft** [comment]
Certainly. Fastlane was not yet set up on my end as you never signaled it's ready :rofl: Well, once a month my cross-checker would look for it, so I'd have noticed within a few days anyway – but as I did not **yet** it's not yet there. Enabled that now with the exception of screenshots; don't you think 30 screenshots is a bit overdoing it? If you link to an image gallery, that's certainly OK. But with metadata, I'd say 15 would be quite a lot already. While it's quite impressive what I see there (wow, really!): do you think all of them are needed there (especially kepping in mind people with a "cheap" data plan or on "less than ideal" connections/bandwidth)?

**Comment by FrontendCrypto** [comment]
Yes, you are right. I created a PR reducing the number of images. I don't know about signal when is ready.

**Comment by IzzySoft** [comment]
> I created a PR reducing the number of images.

Thanks!

> I don't know about signal when is ready.

I took care of that by subscribing to your PR, so I will receive a notification once it's merged :smile:

**Comment by FrontendCrypto** [comment]
> > I created a PR reducing the number of images.
> 
> Thanks!
> 
> > I don't know about signal when is ready.
> 
> I took care of that by subscribing to your PR, so I will receive a notification once it's merged :smile:

Oh! Sorry I completely misunderstood you 😅

**Comment by IzzySoft** [comment]
No prob, we managed :rofl:

**Comment by KoalaSat** [comment]
Hi again @IzzySoft an user just noticed that we had again some warnings of anti features https://apt.izzysoft.de/fdroid/index/apk/com.nostros the script https://github.com/iBotPeaches/Apktool/raw/master/scripts/linux/apktool didn't raised any problem and this time I have no clue of which library is the responsible

**Comment by IzzySoft** [comment]
@KoalaSat you can always check with the libraries section in my repo's web interface. Or use my library scanner yourself, it's all FOSS :smiley: For a guide, please see: [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2).

![image](https://user-images.githubusercontent.com/6781438/224400354-5502e8ce-f410-489a-9c9d-8bf0ff3f0068.png)

The culprit is MLKit, dragging in the other dependencies. Why do almost all Nostr clients include that one now? QR Codes I guess, but there are alternatives – apps like Conversations (XMPP) show that's possible.

**Comment by KoalaSat** [comment]
I think your guess is correct I recently included a QRCode reader library, thanks for you help!

**Comment by IzzySoft** [comment]
Thank you for taking these things seriously! Keeping my fingers crossed then you find an easy replacement that works to your full satisfaction :crossed_fingers:
