### ISSUE TITLE
Bug/Feature: Going back to home doesn't keep scroll

### ISSUE THREAD

**Issue by diegogurpegui** [KoalaSat/nostros#108]
When opening specific notes (or threads), navigating back to the Home timeline resets the scroll to the top. It's king of annoying over time when you use the app a lot.

It would be nice to keep the scroll position

From a technical POV we should keep the timeline on memory (the entire screen probably). Not clear it from memory to be more precise. If we want to persist over re-opening of the app then a more sophisticated solution might be required, like keeping a reference of the note visible on the screen, for accounting of new notes that could appear between close and open.

**Comment by KoalaSat** [comment]
This is already working with the latest changes on navigation of the new UI 👍
