### ISSUE TITLE
Bug: Reply button covers last note of the thread

### ISSUE THREAD

**Issue by diegogurpegui** [KoalaSat/nostros#109]
When looking at a thread, the FAB for Reply is hovering and blocking part of the last note (bottom) on the thread.
This could be easily solved by adding some padding at the bottom of that screen, so when you scroll to the bottom you always have blank space that allows you move the note to the visible area.

**Comment by KoalaSat** [comment]
Hello @diegogurpegui , I kept this into consideration while implementing the new UI, do you want to have a look?

**Comment by diegogurpegui** [comment]
I just took a look and it works well now, thanks! :+1:
