### ISSUE TITLE
app version is not properly encoded into APK

### ISSUE THREAD

**Issue by khimaros** [KoalaSat/nostros#118]
i use a [OSSTracker](https://f-droid.org/en/packages/com.jroddev.android_oss_release_tracker/) to watch for new nostros releases.

because nostros reports 1.0 as the APK version, it always thinks a new version is available.

**Comment by KoalaSat** [comment]
This is being discussed on https://github.com/KoalaSat/nostros/issues/107 , the code in main already includes the real versioning but still I didn't create a new release, if everything works next release will include it

**Comment by khimaros** [comment]
thanks! closing this one as duplicate of https://github.com/KoalaSat/nostros/issues/107
