### ISSUE TITLE
Unable to add relays

### ISSUE THREAD

**Issue by kirkawolff** [KoalaSat/nostros#177]
In v0.2.1.2-alpha on pixel6pro GrapheneOS android13; when I try to add a relay by pressing the + circle, paste it in the field, then press the add button below, I get a toast message that it was added to the list, but the new relay doesn't show up. Later, if I try to add another without backing out, the add button (sometimes loses its color) contains no text, and if I press the blank add button the toast does not appear. If I try to "disable" a relay by using the switch to its right, it appears to also delete it from the list.

**Comment by KoalaSat** [comment]
Thanks for the report! Can you share here what's the exact string you are pasting?

**Comment by KoalaSat** [comment]
I just noticed that window was totally skiped during the UI migration, we'll make it look better 😅

**Comment by KoalaSat** [comment]
I fixed this on `main`, will be fixed with the next release

**Comment by KoalaSat** [comment]
This issue should be fixe with the latest version, can you confirm @kirkawolff ?

**Comment by mat-l** [comment]
I am now able to add my own relay and as per my relay logs, the connection is working.

Also in the sidebar the number of relays is correct, in the overall menu the buttons are not switching of if a relay got deactivated.
![Screenshot_20230128_141332](https://user-images.githubusercontent.com/5571947/215268951-6d3815e1-5a1b-4d74-b0e1-b66095cc4a2e.jpg)
![Screenshot_20230128_142800_com nostros](https://user-images.githubusercontent.com/5571947/215268955-969a028c-f095-4648-9516-e0d1fd1c7d37.jpg)

**Comment by KoalaSat** [comment]
The switc off was another issue I fixed on `main` should be working with the next release

**Comment by kirkawolff** [comment]
Big improvement. I confirm its working as intended on my system. Thank you!
