### ISSUE TITLE
I'm following 80 people, nostros only shows 24

### ISSUE THREAD

**Issue by mikedilger** [KoalaSat/nostros#178]
I'd like to use this as my android client, but it isn't following all the people I'm following, it has very few of the messages I follow, and I haven't been able to figure out how to get it to load all the messages from all the people I follow.  I don't dare edit anything in nostros like my follow list until I'm sure it's not going to delete all my followers.

**Comment by KoalaSat** [comment]
the list of contacts stores on a single event so that means you got all or none. Is it possible you are not connected to a relay with the latest state of your contacts so Nostros just found an old one?

**Comment by mikedilger** [comment]
I'm connected to at least two relays with my latest data.  I don't know how to tell it to subscribe to my contact list, or refetch, or whatever. Killing and restarting doesn't change it. Still says I'm following 24 people.

I can't seem to add relays (I type them in and press add but they don't show up in the list).

**Comment by KoalaSat** [comment]
Yep adding releases were broke with the UI refactor, on the next release should be fixed, can you share you pubkey and the list or relays?

**Comment by mikedilger** [comment]
npub1acg6thl5psv62405rljzkj8spesceyfz2c32udakc2ak0dmvfeyse9p35c
wss://nostr-pub.wellorder.net
wss://nostr-relay.untethr.me
wss://nostr-relay.wlvs.space
wss://nostr.mikedilger.com
wss://nostr.oxtr.dev
wss://nostr.zebedee.cloud
wss://relay.snort.social

**Comment by KoalaSat** [comment]
I'm on the main version with the fix for relays, added your list of relays and I actually see you 80 contacts, probably the latest update is is stored in one you cannot add, the release with the fix for the relays page will be out probably tomorrow so you can test it then 🙂

**Comment by KoalaSat** [comment]
I'll investigate more on this then, I'll let you know my findings

**Comment by KoalaSat** [comment]
I found an specific situation where contacts where not being stored, the fix to that will be in the nest release

**Comment by KoalaSat** [comment]
The release is out, please let me know if it works for you now 🙂

**Comment by mikedilger** [comment]
It is working now.
