### ISSUE TITLE
Add contact button overlapped in Contacts

### ISSUE THREAD

**Issue by ChillerKrypt** [KoalaSat/nostros#181]
Hi to start with thank you.
I'm running nostros 0.2.1.2-Alpha which i got from Droid-ify provided by IzzyOnDroid.
My device is a Samsung Note 20 Ultra 5g SM-N986B
On one-ui version 5.0
Android 13
Baseband N986BXXU5GVL2
Not sure if you need anything else.
As per the screenshot you can see:

The add contact field and the cancel button overlap the Add Contact button
Thought id just give a heads up as this is alpha and all things will be ironed out.
Thank you KoalaSat :+1:
 
![Screenshot_20230125_230129_Nostros](https://user-images.githubusercontent.com/102599587/214560932-32bcb8ce-d244-4229-b05b-03ad3f91be1e.png)

**Comment by KoalaSat** [comment]
Can you confirm this is the latest version?

**Comment by ChillerKrypt** [comment]
@KoalaSat hi hi,
No, nostros 0.2.1.2-Alpha which i got from Droid-ify provided by IzzyOnDroid.
As i see here in github there is .3-alpha.
Want me to try .3-alpha or ?

**Comment by KoalaSat** [comment]
I looks like if the CSS is not applying properly on your device, did you noticed something else looking weird?

**Comment by KoalaSat** [comment]
Maybe we can give a try to .3 just to confirm the issue

**Comment by ChillerKrypt** [comment]
Hi hi. I tried .4 as i saw it go up 3hours ago. So its fixed the overlapping matter which is good, now another issue if you like ill open up a new issue. 

As per screenshots
![Screenshot_20230126_214826_Nostros](https://user-images.githubusercontent.com/102599587/214818646-7272adbe-b8d3-4346-95db-ca81e83dcd18.png)
![Screenshot_20230126_214840_Nostros](https://user-images.githubusercontent.com/102599587/214818655-7f920eb9-b0fc-4056-be46-8400273bbe7d.png)
![Screenshot_20230126_214856_Nostros](https://user-images.githubusercontent.com/102599587/214818658-c737e63a-c956-4bee-9302-4a8231cb65b9.png)
![Screenshot_20230126_214915_Nostros](https://user-images.githubusercontent.com/102599587/214818662-25684967-4d81-4858-a949-6f62a293f1ad.png)

The cancel text dissapears , the add contact text dissapears , cancel text half shows and all show. This occurs when clicking the lite square add contact icon and then ick the cancel button every second or so

**Comment by KoalaSat** [comment]
Yep I'm aware of this this is something regarding the bottom drawer library, I have a pending spike for thisz we can keep this issue for following this up

**Comment by KoalaSat** [comment]
I thin I fixed this last report with the latest release, please let me know if it's working for you 🙂

**Comment by ChillerKrypt** [comment]
@KoalaSat .6-alpha has fixed it 👍thank you.
