### ISSUE TITLE
Show Connected Relays on User Profiles

### ISSUE THREAD

**Issue by nerd2ninja** [KoalaSat/nostros#187]
When viewing someone's profile, show what relays they are connected to in order to ensure users stay connected to people they follow.

(A quick add button would be nice too)
When viewing a user profile, near the area that displays which relays that user is connected to, have a button to connect to all relays that user connects to.

**Comment by KoalaSat** [comment]
This is a good idea! @FrontendCrypto

**Comment by FrontendCrypto** [comment]
Maybe I'm wrong, but if this can be done at the client level it's because the protocol allows it, therefore whoever wants to access that information can do it anyway.

**Comment by KoalaSat** [comment]
@FrontendCrypto is right, all this information is public and 100% available, with a simple script to the top 400 relays I can obtain in 30 seconds all this information without your private key.

The point here is to expose what are the shared relays with the specific contact

**Comment by KoalaSat** [comment]
Take into consideration the Nostr protocol is not about privacy, even encrypted direct messages leaks nowadays certain information (who, when and how often are you talking to).

**Comment by nerd2ninja** [comment]
Different protocol, different design considerations. NOSTR does not make tor obsolete (but you can use them together) nor does it make obsolete other messaging platforms that do more to protect metadata: https://oxen.medium.com/the-state-of-private-messaging-applications-5e7dc0614ef7 

What it does do, is make it easier to switch who is hosting (or relaying) your very public global messages to the world in such a way that no individual relay is able to cut off your voice (to the people looking to hear it).

**Comment by KoalaSat** [comment]
This was release with v0.2.2.4, now the user actions contains the relays button with the list of relays where at least one user action was found
