### ISSUE TITLE
Show Follower/ing on someones Userprofil

### ISSUE THREAD

**Issue by SiriusLightning21** [KoalaSat/nostros#188]
Is it possible to see wich User followed/ing a profil when you klick on a Userprofil. That would be nice for better connection and no need to search for the npub. So you can direct follow there followers or the people the user is following.

**Comment by KoalaSat** [comment]
It's technically possible, but will require some changes on the DB because right now it's user oriented.

Some food for toughs @FrontendCrypto

**Comment by FrontendCrypto** [comment]
Good morning! That would be a great feature. 

This afternoon I will design a couple of proposals for this.  I will post them in the Telegram group to see which one has the most acceptance.

**Comment by KoalaSat** [comment]
I'll close this issue, getting that information is bad for the battery, the data consumption and the relay performance.

 Maximum we can do is to display if the specific user follows you.
