### ISSUE TITLE
crash on login for past several versions

### ISSUE THREAD

**Issue by khimaros** [KoalaSat/nostros#213]
the first few GH releases were working fine but since about 3 weeks ago the app consistently crashes on login with my main private key.

I've cleared storage, reinstalled, etc. none help. everything works fine in amethyst, nostros, and many web clients.

`npub159arpjcey40pe7dtg5jkn2g2mljntqrt32q46aruam0eg897tgdqpj8xxq`

**Comment by KoalaSat** [comment]
Hi thanks for reporting, I managed to enter with your pubkey. Did you also tested accessing to the app with this pubkey? What's the format you are using for your private key?

**Comment by khimaros** [comment]
@KoalaSat just received another update from F-Droid. cleared storage to try with my pubkey as you suggested (which worked). then after logout and back in with private key it is working!
