### ISSUE TITLE
[BUG][0.2.2.0]The first time login will auto block all users.

### ISSUE THREAD

**Issue by chenshaoju** [KoalaSat/nostros#230]
Sorry for my English.

After installing nostros, and login with a private key, the nostros will auto-block all users, including me.

Android OS: Android 9
Phone: Oneplus 5T

Screenshot:
![Screenshot_20230203-005639](https://user-images.githubusercontent.com/515763/216391021-04ed4e5e-39d7-4a67-8c64-cd926049ebec.jpg)

If need any information, please feel free to ask, thank you.

**Comment by KoalaSat** [comment]
Thanks for reporting, This is a visual bug the user doesn't really get blocked, I need to investigate this since looks like only happens in certain Android versions, what's yours?

**Comment by chenshaoju** [comment]
Thanks for the reply,here is CPU-Z screenshot from phone:
![Screenshot_20230203-090254](https://user-images.githubusercontent.com/515763/216488559-78914fe8-f28d-4dfe-a6db-5e5a229b5814.jpg)

![Screenshot_20230203-090440](https://user-images.githubusercontent.com/515763/216488587-ff2dc5d0-5413-4697-8eb2-afad36210ff1.jpg)

**Comment by KoalaSat** [comment]
Hello @chenshaoju version 0.2.2.2 has some code to try to fix the problem, can you test it out? in case there is no change, can you try to uninstall the app and install it again?

**Comment by chenshaoju** [comment]
Thank you, this issue has been fixed.

I'm using `nostros-v0.2.2.3-alpha-arm64-v8a.apk` now. 

cheers!🍻
