### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by iiaannn** [KoalaSat/nostros#248]
Hi,may i know how to contribute for the translation of Chinese, i am not a develper, but i can help to translate it, thank you😆

**Comment by KoalaSat** [comment]
That would be awesome! Are you familiar with Git?

**Comment by iiaannn** [comment]
> 

only a little

**Comment by KoalaSat** [comment]
I can help you by creating a file for Chinese with the english text so you just need to edit the file I can do it now 😃

**Comment by KoalaSat** [comment]
correct if I'm wrong but the code for Chinese is `ZH` right? I create this https://github.com/KoalaSat/nostros/blob/main/frontend/Locales/zh.json

you just to edit the English sentences on the right of the `:`(don't touch the ones on the left). You can even do this on the github web editor, you just need to click on choose this option once you are done.

<img width="898" alt="Screenshot 2023-02-05 at 13 32 10" src="https://user-images.githubusercontent.com/111684255/216818841-c1001223-d257-4211-ba3a-f4c30cda1307.png">

**Comment by iiaannn** [comment]
may the name ZH-CN is better
Okay, i will try it later as you said

**Comment by iiaannn** [comment]
Hi, the translation is done,

**Comment by KoalaSat** [comment]
Where did you create it? I can't find any PR

**Comment by iiaannn** [comment]
> Where did you create it? I can't find any PR

![image](https://user-images.githubusercontent.com/50198347/216966301-21374ff0-1394-4865-b658-630b21d3948f.png)
i updated it in my fork, but yet to know how to make PR😥

**Comment by KoalaSat** [comment]
if you are having troubles I can just go to your fork and copy paste the file :)

**Comment by iiaannn** [comment]
i tried to make a pull request, but not sure it succeeded, if not, please help to copy and paste it, thank you

**Comment by KoalaSat** [comment]
The PR is great thanks! I'll merge it for the next release!

**Comment by KoalaSat** [comment]
@iiaannn I'll close this issue, please feel free to open more PR updating the JSON file at any time 🙂 thanks for the effort!!
