### ISSUE TITLE
Feature request: NIP-06 mnemonic support

### ISSUE THREAD

**Issue by andronoob** [KoalaSat/nostros#249]
[NIP-06](https://github.com/nostr-protocol/nips/blob/master/06.md)

For example: cryptocurrency wallet apps generally strongly dissuade users from just copy-pasting the private key as it's prone to data leak (like, a rogue app which monitors the clipboard and automatically upload its content). Instead these apps guide users to write a mnemonic down on paper.

**Comment by KoalaSat** [comment]
Let's see how can we integrate this on the login page @FrontendCrypto

**Comment by FrontendCrypto** [comment]
Oh yes, that will be a nice thing to design. Going for it in a moment.

**Comment by FrontendCrypto** [comment]
Do you think something like that would make sense?

![image](https://user-images.githubusercontent.com/4659020/216846044-2f62a24b-35e6-4d00-a7ae-3b21c858c9d2.png)

I created a simple prototype, just hit "Create account" and interact.
https://www.figma.com/proto/ZY2QeasyxpDbqzLyHj8zpu/NostrOS?page-id=20%3A59080&node-id=1096%3A75413&viewport=-5458%2C-6620%2C0.34&scaling=scale-down&starting-point-node-id=1096%3A75413&show-proto-sidebar=1

**Comment by KoalaSat** [comment]
I think that's not possible

**Comment by KoalaSat** [comment]
First iteration released with https://github.com/KoalaSat/nostros/releases/tag/v0.2.2.5-alpha

**Comment by KoalaSat** [comment]
Please let us know your feedback @andronoob
