### ISSUE TITLE
[Request] Hitting home tab bring me on top

### ISSUE THREAD

**Issue by serrq** [KoalaSat/nostros#251]
When I already am in home tab it happens that I scroll the feeds and not more I am on top of the list.

Simply hitting the home tab and quickly lift on top again.

**Comment by KoalaSat** [comment]
Implemented! will be included with the next release :)

**Comment by KoalaSat** [comment]
Released with https://github.com/KoalaSat/nostros/releases/tag/v0.2.2.4-alpha

**Comment by KoalaSat** [comment]
I'm not, do you have more info?

**Comment by KoalaSat** [comment]
I think this all depends on the repo (IzzyDroid) to implement this, so if they do it, it should be applied to nostros updates automatically
