### ISSUE TITLE
"Amount (sats)" field rises full size keyboard

### ISSUE THREAD

**Issue by serrq** [KoalaSat/nostros#253]
![Screenshot_2023-02-06-07-56-50-73_5c73a23a736fb25cbee05f6b3c0a142a](https://user-images.githubusercontent.com/113377431/216904124-1ba3f7a8-adeb-4600-860c-25fa5f0dc340.jpg)

Is it possible having a dedicated numerical keyboard?

**Comment by KoalaSat** [comment]
Done! will be included with the next release :)

**Comment by KoalaSat** [comment]
released with https://github.com/KoalaSat/nostros/releases/tag/v0.2.2.4-alpha
