### ISSUE TITLE
Refresh doesent refresh

### ISSUE THREAD

**Issue by kirkawolff** [KoalaSat/nostros#271]
Nostros does not pull latest posts after initial pull. To reproduce: open app, look at "my feed", switch to another app, several hours later switch back to nostros. The feed will not refresh automatically and will not respond to 'pull down' refresh. If you switch to global feed, then back to personal feed, then it seems to reconnect and pull latest posts. It also works to go to hamburger menu, select 'about' then go back to personal feed. This behavior is consistent across about the past dozen versions.

**Comment by KoalaSat** [comment]
Dev notes;

1. The connection is on the websocket
2. The app stores the latest subscription
3. The user pulls to refresh and resend the same subscription request
4. The connection pool detects the same connection is and blocks it from sending it to Java, where the reconnection happens

We need to find a trigger that detects when the app is back from background and clean up all all actives connectiom on the `relaypoll`

**Comment by KoalaSat** [comment]
Will be fixed with the next release

**Comment by KoalaSat** [comment]
Fixed with https://github.com/KoalaSat/nostros/releases/tag/v0.2.2.7-alpha
