### ISSUE TITLE
Some Users cannot be blocked

### ISSUE THREAD

**Issue by 123vier** [KoalaSat/nostros#288]
When clicking on the profile in global feed, and the profile card opens, the 'block' button is without function. It seems it happens when instead of a user name, a pub key in this format is shown

aaaaaaa:aaaaaaa

The other buttons are working.

I found two examples in my global feed, for all other profiles the block button works fine. Example

npub12uhunrz7h57375tj7kakyn5hksyxh8vadh5wc5azxvvagxgjgeuqygm505

**Comment by KoalaSat** [comment]
Thanks for reporting, the scope of user that cannot be blocked are those with no profile name(metadata), will be fixes for the next release

**Comment by KoalaSat** [comment]
Fixed with https://github.com/KoalaSat/nostros/releases/tag/v0.2.2.7-alpha
