### ISSUE TITLE
Some notes do not load

### ISSUE THREAD

**Issue by 123vier** [KoalaSat/nostros#290]
I haven't found a pattern yet, and I would post a link to an example ... but I don't know how ...sorry, another issue incoming ;-)

edit: issue comes up mostly with replies

**Comment by KoalaSat** [comment]
I suppose you meant you never reach to see them? On that it's likely possible those notes are not available on yours relays

**Comment by KoalaSat** [comment]
Or maybe you meant to this? 

https://nostr.build/i/nostr.build_c39a04c51384069a142710fcc432ea3b33ea9473627c2ae03936739d43b2cf9a.png

This actually means that it's a repost with no comments, we have pending to add some visual feedback

**Comment by 123vier** [comment]
> I suppose you meant you never reach to see them? On that it's likely possible those notes are not available on yours relays

Yes thats it, the "loading note" page never arrives to display the note. Maybe until that can eventually  be solved on a protocol level in future, we can get a timeout message after n seconds? "Relay unknown". Or "Enable more relays". I guess there's maybe a possibility to search a directory of relays for that note, or a meta-relay-search-engine in future. Any hint for the user to find a relay for that missing note would be a great start before clients are able to solve this on their own. So my approach was to keep only 4-6 relays active to save battery power. But my "workaround" for not seeing notes quite often is to enable all recommended relays in the Nostros settings. Now most notes are shown.

**Comment by 123vier** [comment]
> Or maybe you meant to this?
> 
> https://nostr.build/i/nostr.build_c39a04c51384069a142710fcc432ea3b33ea9473627c2ae03936739d43b2cf9a.png
> 
> This actually means that it's a repost with no comments, we have pending to add some visual feedback @FrontendCrypto

No, but thanks for fixing this too so quickly. :)

**Comment by KoalaSat** [comment]
Perfect I'll close this on that case
