### ISSUE TITLE
is the public feed means global feed ?

### ISSUE THREAD

**Issue by iiaannn** [KoalaSat/nostros#297]
![image](https://user-images.githubusercontent.com/50198347/217984028-982d5027-c657-4fe6-9c51-50e746b8e8f0.png)
as the picture, i have doubts

**Comment by KoalaSat** [comment]
Yes! good catch, I'll change it for other languages

**Comment by 123vier** [comment]
> Yes! good catch, I'll change it for other languages

lol, I translated "global" and didn't notice public is wrong :)
