### ISSUE TITLE
Profile card relays active list doesn't show more than ten active relays

### ISSUE THREAD

**Issue by serrq** [KoalaSat/nostros#303]
Currently I have nineteen active relays connected but because card list doesn't scroll Nostros shows me only ten. The other nine are unreachable due the scroll lack.

**Comment by KoalaSat** [comment]
Solved with https://github.com/KoalaSat/nostros/releases/tag/v0.3.0.0-alpha, please @serrq let me.kniwnif now works for you

**Comment by KoalaSat** [comment]
No problem IzzyDroid usually updates the repo every day around 20 UTC, we can wait 👍

**Comment by KoalaSat** [comment]
Should be fixed now (again) with the latest version
