### ISSUE TITLE
Remove/Copy Relay card

### ISSUE THREAD

**Issue by 123vier** [KoalaSat/nostros#309]
**Is your feature request related to a problem? Please describe.**
Until recently tapping on a relay in the relay menu brought up a card with 'remove' and 'copy'. It got replaced with "push data" etc.

I like to request this back please :)

**Comment by KoalaSat** [comment]
We need to review those cards and bring that back, yes! thanks!

**Comment by FrontendCrypto** [comment]
Saved issue, updating it in design tomorrow. Thank you!

**Comment by KoalaSat** [comment]
This was already implemented in one of the latest versions 👍
