### ISSUE TITLE
Relays bars have too much similar colours

### ISSUE THREAD

**Issue by serrq** [KoalaSat/nostros#312]
Can I avoid too much similar colors in the relays bars? I mean more contrast.

![Screenshot_2023-02-11-20-59-43-35_5c73a23a736fb25cbee05f6b3c0a142a](https://user-images.githubusercontent.com/113377431/218278844-3f094a60-7fb8-420d-b75d-1e0da7cea8f7.jpg)

**Comment by KoalaSat** [comment]
This was something I was considering cc @FrontendCrypto

**Comment by FrontendCrypto** [comment]
That's weird because there are few relays and there are not repeated colors on palette. Definitely a solution could be override default assigned color.

**Comment by KoalaSat** [comment]
The color is deterministically applied based on the url from a closed list. so doesn't matter the size there will be always repeated colors, I believe giving the option to manually change it might solve the problem right? other option is to increase the list so the possibilities of matching the same color is smaller

**Comment by KoalaSat** [comment]
We doubled the available colours, still possible to see duplicates but less likelly
