### ISSUE TITLE
two pop-up windows

### ISSUE THREAD

**Issue by iiaannn** [KoalaSat/nostros#325]
Hi，when I click on a user's avatar, there will be a pop-up window about the user's operation, when clicked the relay button, it will have one more popup, so when you want to quit the action, there will be two popups, it should be like this: when you click the relay button, the first popup should be hided. And one more, the popup animation has lags, it looks the apps was frozen
p.s. sorry for poor english

**Comment by KoalaSat** [comment]
Hi @iiaannn I'll check this out I'm aware at some point the bottom drawer animation stoped working but I'll try to reproduce what you said, thanks!!

**Comment by KoalaSat** [comment]
Fixed by replacing pop up windows by real windows 👍
