### ISSUE TITLE
'Leave Group' doesn't work

### ISSUE THREAD

**Issue by 123vier** [KoalaSat/nostros#328]
**Describe the bug**
Cannot leave a group

**To Reproduce**
In a group, tap menu and then "Leave group"

Sometime nothing happens, sometimes the channel disappears for a few moments just to come back and I'm still able to enter and read messages

**Comment by 123vier** [comment]
Check out https://github.com/KoalaSat/nostros/releases/tag/v0.3.0.0-alpha

:)

**Comment by KoalaSat** [comment]
Fixed for https://github.com/KoalaSat/nostros/releases/tag/v0.3.0.1-alpha
