### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by iiaannn** [KoalaSat/nostros#333]
Hi，i am using Samsung oneui 5.0, it is based on android 13, every time when i open the app, it will crash first then open again automatically, it happens every time. 
And also in the profile page, the language item's value is shown in wrong color, cannot see clearly

**Comment by KoalaSat** [comment]
Did you try reinstalling?

**Comment by iiaannn** [comment]
it looks work for me, thanks bro

**Comment by iiaannn** [comment]
after used for a short time, startup crash again

**Comment by KoalaSat** [comment]
Does it happens always? Did you manage to figure out a pattern?
