### ISSUE TITLE
French short_description much too long

### ISSUE THREAD

**Issue by IzzySoft** [KoalaSat/nostros#343]
your `fr-FR/short_description.txt` has 3172 chars, max allowed are 80 chars – looks like you accidentally put a `full_description.txt` there. All after char 80 will be cut off as per Fastlane definition – so please take care :wink:

**Comment by FrontendCrypto** [comment]
Guilty 😓. I'll fix it as soon as possible. Sorry for any inconveniences.

**Comment by IzzySoft** [comment]
No worries; as long as it's fixed before the next release is tagged all is fine (I temporarily removed it at my end so it cannot "break stuff" or lead to confusion – but the next update would replace it). It only came to my attention as the automated monthly cross-check found it :wink:

**Comment by KoalaSat** [comment]
Thanks for taking care!

**Comment by IzzySoft** [comment]
We all do our very best¹ – that way results must be fantastic :smile: Thanks for fixing that fast!

----

¹ <sub>I've just implemented checks on-retrieval in addition to the full-repo-scan, so in the future warnings will be thrown already when such a file is pulled, also covering fulldesc & changelogs :wink:</sub>

**Comment by IzzySoft** [comment]
Now the French `full_description.txt` is overlength :see_no_evil:

    com.nostros/fr-FR/full_description.txt has 4002 chars

**Comment by KoalaSat** [comment]
Thanks for reporting! It's there any maximum even if it's not real we can stay attached? cc @FrontendCrypto

**Comment by FrontendCrypto** [comment]
Mmm I am not in front of the computer I think I fixed it weeks ago but maybe I am wrong. I'll review it later.

**Comment by IzzySoft** [comment]
@KoalaSat see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688):

* 500 char for changelogs
* 4000 char for `full_description.txt`
* 80 char for `short_description.txt`

Numbers for pictures in the Cheat Sheet.
