### ISSUE TITLE
Translation in de.json not working

### ISSUE THREAD

**Issue by 123vier** [KoalaSat/nostros#344]
I compared it with en.json and all items are translated. I only noticed that one line was in a different order and corrected this, but as far as I know this shouldn't make a difference inside this section. If there's a syntax error, I cannot find it.

 "menuItems": {
      "relays": "Relays",
      "contacts": "Kontakte",
      "notConnected": "Nicht verbunden",
      "connectedRelays": "{{number}} verbunden",
      "following": "{{following}} folge ich",
      "followers": "{{followers}} folgen mir",
      "configuration": "Einstellungen",
      "about": "Über Nostros",
      "contacts": "Kontakte",
      "reportBug": "Bug melden",
      "logout": "Abmelden"
    },

_Originally posted by @123vier in https://github.com/KoalaSat/nostros/issues/337#issuecomment-1432675067_

**Comment by KoalaSat** [comment]
Thanks for reporting, it should be easy to spot it with my IDE

**Comment by KoalaSat** [comment]
latest version is working for me now, can you check it out?

**Comment by 123vier** [comment]
Yes, it's working now. Great :)

thanks
