### ISSUE TITLE
unable to view invoices

### ISSUE THREAD

**Issue by jawsh207** [KoalaSat/nostros#374]
Unable to view invoices on latest build. They appear in Amethyst. Maybe I'm mistaken but I thought invoices worked in Nostros also.

**Comment by KoalaSat** [comment]
It depends of the format, do you have an example of a note?

**Comment by j-mizzle** [comment]
> 

Here's a note ID of a post I just made "note1mk8uj4ch4ljt54x74w8tavqjlkj9uv642j9ddp3ngphcxxu293qs93km4h". I have had over 10 people post invoices today and not a single one has been visible, I had to open Amethyst to pay them. Also when hitting the zap button it randomly fails to open a wallet or do anything.

**Comment by KoalaSat** [comment]
Do you another way of sharing the note, bech32 `note1` are not officially supported by the protocol that's why it's not implemented on Nostros

**Comment by j-mizzle** [comment]
> 

Not really. Can't seem to figure out how to copy the note via Nostros so I used Amethyst. My npub is "npub1jawsh2wrjk25urgx4qq65fam67nrrkdf4zjxrhcezv5v69g9gxwqyhnew7"
You can look at my profile via Nostros and Amethyst. Lots of invoices posted as replies and none are visible via Nostros but are with other clients.

**Comment by KoalaSat** [comment]
Closing old ones, I was able to etger into that nevent on the latest version and the invoices are displaying correctly 🤙
