### ISSUE TITLE
feature req. remove the anti-functions in izzyondroid

### ISSUE THREAD

**Issue by Wjxfi** [KoalaSat/nostros#408]
tracking, proprietary dependencies.

**Comment by KoalaSat** [comment]
Weird this should be recent, thanks for pointing it out, I'll take a look to see which library is the bad boy

**Comment by KoalaSat** [comment]
The problem was found in the QR reader, I temporally disabled it https://github.com/KoalaSat/nostros/releases/tag/v0.3.1.6-alpha

**Comment by KoalaSat** [comment]
IzzyDroid does not display warning anymore 👍
