### ISSUE TITLE
Include open source video player

### ISSUE THREAD

**Issue by KoalaSat** [KoalaSat/nostros#465]
We want to add an open source de-googled video player. Recently we added  `"react-native-video": "^5.2.1"` but turns out this library uses Google services https://github.com/KoalaSat/nostros/actions/runs/4530735588/jobs/7980037079

The most promising library is https://www.npmjs.com/package/react-native-vlc-media-player but I got errors related with `.so`files not being found.

Any other well maintained video player library is also a good option as far it's FOSS and de-googled.

**Rewarded with 200K Sats ⚡ drop a comment below if you want to be assigned.**

**Comment by jawsh207** [comment]
Is nothing included in AOSP sources? LineageOS?

**Comment by Villatrax** [comment]
What about this? 
[Player.zip](https://github.com/KoalaSat/nostros/files/11309382/Player.zip)

As per your bounty (https://bountsr.org/nostros-video-player-copy/):

bc1qms75lrqnqcgn8up4m6ede2dzp93nhvcelqu8fmmescsy5c0eesksc9hqsy

**Comment by jawsh207** [comment]
Could MPV be used for this? As far as I know it's open source and doesn't depend on Google. Also, from their website:
"A straightforward [C API](https://github.com/mpv-player/mpv/blob/master/libmpv/client.h) was designed from the ground up to make mpv usable as a library and facilitate easy integration into other applications."
MPV is also available on Android via F-Droid and GitHub. I think it may be with looking into.

**Comment by Temidayo32** [comment]
@KoalaSat I am interested in working on this! Can you assign it to me

**Comment by KoalaSat** [comment]
Done @Temidayo32 ! We have a FOSS validator that  runs on every build. Make sure you run it before working on the implementation details to validate the library of your choice is fully FOSS 🙂

**Comment by Temidayo32** [comment]
Oh, I see. Thanks @KoalaSat for assigning me the issue.

**Comment by priyanshunishad4** [comment]
hi @KoalaSat is this bounty open ?

**Comment by KoalaSat** [comment]
> hi @KoalaSat is this bounty open ?

Not anymore, thanks for asking 🙂
