### ISSUE TITLE
Include open source QR reader

### ISSUE THREAD

**Issue by KoalaSat** [KoalaSat/nostros#468]
We want to add an open source de-googled QR reader. Recently we added:
- https://www.npmjs.com/package/react-native-qrcode-scanner
but turns out this library uses `react-native-camera` which uses Google services https://github.com/KoalaSat/nostros/actions/runs/4531654828/jobs/7982068043

It can be tested by doing these changes:
- https://github.com/KoalaSat/nostros/pull/467/files#diff-8bb5616fd0c64509171fba4255b434c0b5bdcb63af15074801a087b21c268047
- https://github.com/KoalaSat/nostros/pull/467/files#diff-1ec9483ede6f8f430214f827b8a59687304223c1c8f8ce32d1dc4ddf986779ab

Any other well maintained QR reader library is a good option as far it's FOSS and de-googled. It looks like the app [Conversations (XMPP)](https://codeberg.org/inputmice/Conversations) makes use of a valid QR reader library.

**Rewarded with 300K Sats ⚡ drop a comment below if you want to be assigned.**

**Comment by b4s36t4** [comment]
Maybe create a plugin for react-native-camera using `zxing` or `https://github.com/LazarSoft/jsqrcode` should be a de-googled package right?!

**Comment by MauroJr** [comment]
@KoalaSat I would love to work on this one! Can you assign it to me?

**Comment by KoalaSat** [comment]
Done @MauroJr ! We have a FOSS validagor that ir run in every build. Make sure you run it before working on the details to validate the library of your choice is fully FOSS 🙂

**Comment by KoalaSat** [comment]
More details here: https://github.com/KoalaSat/nostros/blob/main/.github/workflows/android-build.yml#L34

**Comment by b4s36t4** [comment]
@KoalaSat Can I also work on this?

**Comment by KoalaSat** [comment]
Hi @b4s36t4 , sorry but usually we assign bounties to only one person, if you are interested,  you can also check this one, wich is pretty much similar https://github.com/KoalaSat/nostros/issues/465

**Comment by MauroJr** [comment]
@KoalaSat Thank you for assigning it to me. I hope can help.

I'm working on it outside of my working hours which is GMT -5.

I already made a good part of it and I should have a PR Tomorrow before I finish my day, very late in the evening.

After I push it, I'll be happy to get feedback and discuss the implementation.

**Comment by KoalaSat** [comment]
> @KoalaSat Thank you for assigning it to me. I hope can help.
> 
> I'm working on it outside of my working hours which is GMT -5.
> 
> I already made a good part of it and I should have a PR Tomorrow before I finish my day, very late in the evening.
> 
> After I push it, I'll be happy to get feedback and discuss the implementation.

No rush :) take your time!

**Comment by priyanshunishad4** [comment]
hi @KoalaSat is this bounty open ? if yes can you tell me how to claim?

**Comment by KoalaSat** [comment]
> hi @KoalaSat is this bounty open ? if yes can you tell me how to claim?

Not anymore, thanks for asking 🙂
