### ISSUE TITLE
Android navigation bar

### ISSUE THREAD

**Issue by iiaannn** [KoalaSat/nostros#492]
May support the android navigation bar?
Now it shows as a dark background with the navigation bar, thank you

**Comment by KoalaSat** [comment]
Sorry I think I don't follow you, can you share an screenshot?

**Comment by iiaannn** [comment]
![image](https://user-images.githubusercontent.com/50198347/230566345-f06ee9f2-860f-4f2d-97c2-bf063dbed5a3.png)
![image](https://user-images.githubusercontent.com/50198347/230566420-1a309e6a-304b-4c3f-9ab6-40f8311f28bd.png)
the first is nostros, the second is twitter, Twitter adapts navigation bar immersion, it looks better

**Comment by KoalaSat** [comment]
Fixed in https://github.com/KoalaSat/nostros/releases/tag/v0.3.2.7-alpha
