### ISSUE TITLE
question on libraries used

### ISSUE THREAD

**Issue by IzzySoft** [KoalaSat/nostros#493]
Hi @KoalaSat, I hope for you this is an easy question to answer. My library scanner just reported something "unknown" (i.e. libraries it doesn't yet know), and I couldn't figure out what library/Github-repo their sources might belong to. Can you please help me out with that?

```
/nostr/base/annotation:
/nostr/base/handler/request:
/nostr/base/handler/response:
/nostr/crypto/bech32:
/nostr/crypto/schnorr:
/nostr/event/impl:
/nostr/event/list:
/nostr/event/marshaller/impl:
/nostr/event/message:
/nostr/event/tag:
/nostr/event/unmarshaller/impl:
/nostr/event/util:
/nostr/json/parser/impl:
/nostr/json/unmarshaller/impl:
/nostr/types/values/impl:
/nostr/types/values/marshaller:
/nostr/util:
```

Thanks in advance!

**Comment by KoalaSat** [comment]
Looking at it and if the warning is recent I bet it's https://github.com/KoalaSat/nostr-java which is just a small fork of https://github.com/tcheeric/nostr-java

**Comment by KoalaSat** [comment]
The fork is temporal btw, I'll change soon to the original source

**Comment by IzzySoft** [comment]
So I shall ignore that as it's just in the current version? Or will those "paths" remain, and I should map it to [tcheeric/nostr-java](https://github.com/tcheeric/nostr-java)? Will do the latter now as you'll switch there then. Thanks a lot!

**Comment by KoalaSat** [comment]
Thank you for be always there watching! 😄🚀

**Comment by IzzySoft** [comment]
While on it, there are a few more which I've encountered before and couldn't figure. Their names start with something scary:

```
/com/facebook/debug/debugoverlay/model:
/com/facebook/debug/holder:
/com/facebook/debug/tags:
/com/facebook/fbcore:
/com/facebook/fbjni:
```

Can any of those be clearly assigned to a specific library? I know there are some "crazy nuts" out there using the `com.facebook.` prefix for their packages, which doesn't make it easier…
