### ISSUE TITLE
Issues loading timelines and posting notes

### ISSUE THREAD

**Issue by jawsh207** [KoalaSat/nostros#503]
Seem to be having an issue loading timelines and also when posting notes it hangs on hitting the send button. Force closing fixes the issue temporarily, becomes a pain repeating the process tho. I've tried wiping all data and fresh installs of both the universal build as well as arm64-v8a builds.

**Comment by KoalaSat** [comment]
What kind of issue? frozen app?

**Comment by jawsh207** [comment]
> What kind of issue? frozen app?

Not frozen. Just loads endlessly. When posting a note, hitting send just spins without posting anything.

**Comment by KoalaSat** [comment]
Cleaning up old issues
