### ISSUE TITLE
App crash in DM section

### ISSUE THREAD

**Issue by Wyckoffan** [KoalaSat/nostros#504]
**Describe the bug**
The app crashes when trying to write a message in the message section (DM). When text field is active the app crashes before the keyboard comes up. I am using Anysoft Keyboard instead of GBoard.

**To Reproduce**

1. Go to specific contact profile and hit 'Message'
2. Click on 'Type Message'
3. See error (app crashes)

**Comment by jawsh207** [comment]
I've had this issue as well. I run deGoogled Android and use FlorisBoard as my keyboard.

**Comment by KoalaSat** [comment]
Fixed in https://github.com/KoalaSat/nostros/releases/tag/v0.3.2.7-alpha
