### ISSUE TITLE
Add nostr-tools dependecy

### ISSUE THREAD

**Issue by arejula27** [KoalaSat/nostros#54]
There is a protect which implement the basic protocol function. https://github.com/fiatjaf/nostr-tools
I'm improving the TS interface. It would be a good option because you can focus on other  things, instead implementing the newest nip.

**Comment by arejula27** [comment]
I saw you want to manage the ws connections after a long inactivity time, with this library it is possible too, you can develop the logic and call connect/ close connection on each relay

**Comment by KoalaSat** [comment]
Hi @arejula27, Nostros already does a limited use of nostr-tools https://github.com/KoalaSat/nostros/blob/df8a69d923ad7d4c49f926af5be88c142eab216c/frontend/Components/ConversationPage/index.tsx#L14

Initially I wanted to use it as base library of the app, but I ended up facing 2 main problems:
- nostr-tools implements a version of ECMAScript not compatible with Android. If I remember correctly, it requires 2021 and Android is limited to 2019.
- React-Native has a single thread to manage everything related to JS (views included), so doing and intensive use of background tasks (for example relays communication) affected really badly to the performance resulting even in the app completely freezing for seconds.

This is why I decided to re-implement everything that can be parallelized in Java, it was the only way to have a good performance.

**Comment by dskvr** [comment]
Have you tried @jb55's `nostr-js`?

**Comment by KoalaSat** [comment]
Yes I did but it was missing some functions I needed, I assumed `nostr-tools` was a most recent version, and decide to go forward with the Java version, as I said, the background jobs with JS affects a lot the UX

**Comment by arejula27** [comment]
On this case i think you made the correct decision, good luck. I cant wait for using nostros :D
