### ISSUE TITLE
New branding

### ISSUE THREAD

**Issue by FrontendCrypto** [KoalaSat/nostros#69]
I open this issue in order to discuss proposals for new branding. Below is my proposal for the logo redesign, starting from the original idea.

![01](https://user-images.githubusercontent.com/4659020/209578392-903db8e1-aca9-4971-ae89-8be8a23dbcc6.png)

![02](https://user-images.githubusercontent.com/4659020/209578395-b74235f4-e58e-4b97-8e9c-c77d906acb40.png)

![03](https://user-images.githubusercontent.com/4659020/209578396-0af17e79-5092-4d51-b439-653fe03130b5.png)

![04](https://user-images.githubusercontent.com/4659020/209578397-1529aabd-a1af-4f45-a1e1-c87a6af105b7.png)

![05](https://user-images.githubusercontent.com/4659020/209578399-87628a73-2244-4bac-83c0-662f66354612.png)

![06](https://user-images.githubusercontent.com/4659020/209578400-85e0f986-f325-461c-a44e-893850cb9da5.png)

![07](https://user-images.githubusercontent.com/4659020/209578401-30293664-b080-4ec6-94e2-18bcd9002cb6.png)

![08](https://user-images.githubusercontent.com/4659020/209578403-7732aeb4-4f3f-42b3-aae9-bba77eff0434.png)

![09](https://user-images.githubusercontent.com/4659020/209578404-30fd4824-a10e-4885-8a60-43f8e34af21c.png)

![10](https://user-images.githubusercontent.com/4659020/209578406-f77cfe94-e92e-4102-a48d-5274aa069ad7.png)

![11](https://user-images.githubusercontent.com/4659020/209578408-bed4ec2e-2fde-4c90-85ac-ba3ae9115544.png)

![12](https://user-images.githubusercontent.com/4659020/209578409-1345c976-c29f-4107-9420-a8fd28cdb7cb.png)

**Comment by KoalaSat** [comment]
Thank you so much!! the logo needed a really good simplification like this one.

 I would like to leave here the intention of the original logo for the record and to try to share some ideas.

Originally, the logo were supposed to have only 2/3 parallel dotted lines (representing relays) with no center (representing the decentralized nature of the protocol). 

In addition, I wanted to remove some dots from those lines but still enough to keep the circled shape and represent that even with some missing dots(relays) the network wouldn't be affected.

**Comment by diegogurpegui** [comment]
I like the new style!
