### ISSUE TITLE
Upgrading the app leads to loss of all information.

### ISSUE THREAD

**Issue by xavierfiechter** [KoalaSat/nostros#81]
Add local storage / caching?

**Comment by KoalaSat** [comment]
This is the first time I get this report, so far people has been upgrading it without losing the data. The app has a local DB plus a `SecureStorage` instance to store keys. Can you provide more info?

**Comment by xavierfiechter** [comment]
That was an issue on my end. Sorry. 
One instance of the app was running in the business profile of the phone.
