### ISSUE TITLE
Improve UX by adding more visual feedback

### ISSUE THREAD

**Issue by diegogurpegui** [KoalaSat/nostros#98]
The user needs more visual feedback when using the app. Like when something goes wrong, or when something works. Even UI hints helps.
I had some issues with the app and I didn't even know what happened.

I'll open a PR for this :wink:

**Comment by KoalaSat** [comment]
Hi @diegogurpegui , actually we have an issue opened for a drastic change on the UI https://github.com/KoalaSat/nostros/issues/69  so this looks like the right moment to propose and discuss about this topic

**Comment by diegogurpegui** [comment]
Saw that issue yesterday and I really liked the new proposed branding. Once it's done it'll be worth to review this usability considerations.

**Comment by FrontendCrypto** [comment]
Hi, sorry, I completely forgot to share my progress with the design here. I leave you a public link to Figma with the design, all kind of critics and feedback are more than welcome, although I'm still working on it.

https://www.figma.com/file/vEwMCu1AAXrdqvXEbcYJ8b/Nostros-(Public)?node-id=0%3A1&t=ii4lqRLHpC1dADRG-1

**Comment by diegogurpegui** [comment]
Looking into it, looking great so far!
BTW, I believe this link should be in the issue #69 :stuck_out_tongue:

**Comment by KoalaSat** [comment]
Hey @diegogurpegui we have the UI already implemented! did you take a look? any feedback regarding this topic?

**Comment by diegogurpegui** [comment]
I did see visual feedback in the buttons when sending a message :+1: . Didn't look at all cases (the error cases are less frequent to test).
